### PR TITLE
Update NYCweatherAPI.py

### PR DESCRIPTION
**Pull request by sbg389**
parse API response and load into dictionary object

### CODE REVIEW

**Comment by fedhere** [comment]
I think you submitted this pull request by mistake. A pull request means you made changes to my code that you think I should apply, because you found a mistake or something should be improved.

**Comment by sbg389** [comment]
Hi,

Its a small suggestion on your weather api sample, maybe I am off, but I
used it for the HW2 and I think on the sample you were not assigning to a
variable the dictionary representation that you get after you invoke the
json.loads method on response from the API.

At the end you print the actual string representation that you got before,
and that works on the sample (the difference between the string and the
dict its hard to notice on a print) but if you try to use the object  later
as a dictionary, which is what I thought had  after invoking json.loads, it
throws an error.

**Comment by fedhere** [comment]
Excellent point! I will accept the pull request now that I understand it. 
A note: please always leave a comment on your pull request, which explains why you think the change should be embraced. Particularly for this class since students often click on the pull request button by mistake! But also in general: unless one expects a pull request from you because they know you are working on something it is time-consuming to understand the request. And even in that case, for book-keeping, all these actions should be accompanied by comments!

**Comment by sbg389** [comment]
will certainly do, thanks (I guess the "parse API response and load into
dictionary object" comment was a little to synthetic :) )

**Pull request merged**
